In [1]:
### numpy-> Play with arrays
### pandas-> dataset
### matplotlib-> data visualisation
###seaborn-> data visualisation
### scipy-> statistical
### sklearn-> algorithm





In [2]:
import numpy as np
simple_list=[6,7,9]
np.array(sample_list)

NameError: name 'sample_list' is not defined

In [3]:
simple_list=[6,7,9]
np.array(sample_list)

NameError: name 'sample_list' is not defined

In [ ]:
arr=np.array([6,7,9])

In [4]:
np.arrange(5,15)

AttributeError: module 'numpy' has no attribute 'arrange'

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [7]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [9]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [10]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [11]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [16]:
np.random.rand(3,5)

array([[0.94547939, 0.43367515, 0.1505705 , 0.01302078, 0.21963607],
       [0.2991541 , 0.55315824, 0.48417373, 0.29461486, 0.40186203],
       [0.04364956, 0.75985577, 0.96630527, 0.91908435, 0.30440688]])

In [17]:
arr=np.random.rand(2,4)
arr

array([[0.22538497, 0.4569673 , 0.50407634, 0.40103214],
       [0.43332575, 0.73464453, 0.11913538, 0.63209776]])

In [18]:
np.random.randint(2,100)

90

In [19]:
np.random.randint(20,56,100)

array([49, 51, 42, 38, 51, 47, 45, 54, 42, 27, 47, 21, 40, 54, 51, 37, 49,
       46, 50, 23, 38, 35, 55, 35, 27, 39, 20, 35, 53, 41, 21, 47, 31, 24,
       44, 32, 50, 36, 29, 47, 28, 24, 55, 40, 45, 52, 23, 37, 30, 40, 38,
       28, 48, 46, 27, 34, 39, 30, 32, 45, 52, 39, 39, 30, 43, 47, 40, 45,
       38, 27, 21, 45, 32, 48, 37, 55, 33, 53, 51, 48, 48, 50, 45, 36, 25,
       48, 45, 53, 53, 29, 33, 32, 53, 54, 27, 52, 26, 21, 47, 55])

In [20]:
np.random.randint(10,23,99)

array([10, 18, 10, 13, 14, 12, 16, 18, 11, 18, 15, 20, 18, 19, 15, 19, 17,
       18, 20, 16, 11, 10, 12, 10, 20, 16, 22, 16, 18, 15, 10, 18, 16, 18,
       20, 17, 20, 21, 19, 18, 11, 18, 11, 13, 10, 22, 16, 19, 13, 17, 13,
       13, 13, 15, 16, 19, 10, 13, 10, 22, 19, 17, 13, 13, 18, 13, 18, 21,
       17, 16, 14, 21, 13, 19, 20, 13, 12, 21, 15, 10, 12, 11, 13, 18, 14,
       20, 19, 11, 14, 22, 20, 22, 13, 18, 21, 13, 15, 13, 16])

In [21]:
sample_array=np.arrange(30)
sample_array

AttributeError: module 'numpy' has no attribute 'arrange'

In [22]:
rand_array=np.random.randint(0,10,50)
rand_array

array([4, 8, 3, 7, 7, 0, 1, 1, 5, 5, 6, 4, 6, 7, 6, 6, 2, 8, 4, 2, 9, 9,
       4, 5, 0, 9, 3, 6, 6, 3, 2, 7, 3, 7, 4, 6, 5, 2, 1, 7, 2, 7, 4, 5,
       2, 5, 9, 8, 9, 3])

In [24]:
smaple_array.reshape(5,6)

NameError: name 'smaple_array' is not defined

In [25]:
smaple_array.reshape(5,6)

NameError: name 'smaple_array' is not defined

In [26]:
rand_array.max()

9

In [27]:
rand_array.argmax()

20

In [28]:
a=np.eye(5)

In [29]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a.np.random.rand(2,3)

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [32]:
a.np.random.rand(2,3)

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [34]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
sample_array=np.arrange(10,11)

AttributeError: module 'numpy' has no attribute 'arrange'

In [36]:
sample_array=np.arrange(10,21)

AttributeError: module 'numpy' has no attribute 'arrange'

In [38]:
sample_array=np.arrange(10,21)


sample_array

AttributeError: module 'numpy' has no attribute 'arrange'

In [39]:
sample_aarray[0]

NameError: name 'sample_aarray' is not defined

In [40]:
sample_array[2:5]

NameError: name 'sample_array' is not defined

In [41]:
sample_array=np.arange(10,21)

sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
sample_array(0)

TypeError: 'numpy.ndarray' object is not callable

In [43]:
sample_array[2:5]

array([12, 13, 14])

In [44]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [45]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [47]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [48]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional Array